server:
  port: 9003
spring:
  application:
         name: zuulproxy
zuul:
   routes:
     employeezuul:
             path: /emp/**
             service-id: employeezuul
     departmentzuul:
             path: /dept/**
             service-id: departmentzuul
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

             